POST http://localhost:3333/login
Content-Type: application/json

{
  "username": "jefferson1104",
  "password": "123456"
}

###
GET http://localhost:3333/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJKZWZmZXJzb24gU29hcmVzIiwidXNlcm5hbWUiOiJqZWZmZXJzb24xMTA0IiwiZW1haWwiOiJqZWZmZXJzb25Ac29hcmVzZGV2LmNvbSIsInJvbGUiOiJhZG1pbiIsImxvZ2luRGF0ZSI6IjEwLzA5LzIwMjEiLCJpYXQiOjE2MzEyNDg3OTAsImV4cCI6MTYzMTI0ODg1MH0.QdlUt_Xnr7QLqBhpvBSwtftfDrpUfyIIkBTrOZrJvJQ
